import os
import struct

class SovereignBootstrapCompiler:
    def __init__(self):
        # Match the exact binary opcode allocations defined in spec/bytecode_isa.md
        self.OPCODES = {
            'CONNECT':  0x01,
            'RESONATE': 0x02,
            'COLLAPSE': 0x03
        }
        
        # Match the exact 8-neighbor orthogonal directional byte tokens
        self.DIRECTION_MAP = {
            'x+1': 0x10, 'x-1': 0x11,
            'y+1': 0x20, 'y-1': 0x21,
            'z+1': 0x30, 'z-1': 0x31,
            'w+1': 0x40, 'w-1': 0x41
        }

    def clean_source_line(self, line):
        """Strips out comments and empty whitespace from the stream."""
        cleaned = line.split('#')[0].strip()
        return cleaned

    def compile_line(self, line_num, line_text):
        """Converts a single assembly command line into raw machine bytes."""
        token_string = self.clean_source_line(line_text)
        if not token_string:
            return b''

        parts = token_string.split()
        command = parts[0].upper()

        if command not in self.OPCODES:
            raise SyntaxError(f"[Line {line_num}] Unknown hardware command signature: {command}")

        opcode_byte = self.OPCODES[command]
        binary_packet = bytearray([opcode_byte])

        if command == 'CONNECT':
            # Format requires: CONNECT [Source_Dir] [Dest_Dir]
            if len(parts) != 3:
                raise ValueError(f"[Line {line_num}] CONNECT requires exactly 2 directional operands.")
            
            src, dest = parts[1], parts[2]
            if src not in self.DIRECTION_MAP or dest not in self.DIRECTION_MAP:
                raise ValueError(f"[Line {line_num}] Invalid direction coordinate token.")
                
            binary_packet.append(self.DIRECTION_MAP[src])
            binary_packet.append(self.DIRECTION_MAP[dest])
            return bytes(binary_packet)

        elif command == 'RESONATE':
            # Format requires: RESONATE [Pulse_Value]
            if len(parts) != 2:
                raise ValueError(f"[Line {line_num}] RESONATE requires exactly 1 whole-number value.")
            
            try:
                pulse_value = int(parts[1])
                if not (0 <= pulse_value <= 255):
                    raise ValueError("Pulse value must fit within a single unsigned byte (0-255).")
            except ValueError:
                raise ValueError(f"[Line {line_num}] Operand must be a valid whole-number integer.")
                
            binary_packet.append(pulse_value)
            return bytes(binary_packet)

        elif command == 'COLLAPSE':
            # Format requires: COLLAPSE (Autogenerated global scope checker byte)
            binary_packet.append(0xFF)
            return bytes(binary_packet)

        return b''

    def compile_script(self, source_code):
        """Assembles a full multi-line text script into a raw binary bytecode stream."""
        print("=== BOOTSTRAP ASSEMBLER INITIALIZING ===")
        raw_bytecode = b''
        lines = source_code.strip().split('\n')
        
        for idx, line in enumerate(lines, 1):
            try:
                byte_segment = self.compile_line(idx, line)
                if byte_segment:
                    raw_bytecode += byte_segment
                    print(f" Line {idx} Compiled Successfully -> {[hex(b) for b in byte_segment]}")
            except Exception as e:
                print(f"🔴 COMPILATION CRITICAL FAILURE: {str(e)}")
                return None
                
        print(f"=== ASSEMBLY COMPLETE: Total Payload Size = {len(raw_bytecode)} Bytes ===\n")
        return raw_bytecode

# --- Execute Local Verification Test ---
compiler_unit = SovereignBootstrapCompiler()

sample_script = """
CONNECT x+1 y-1      # Step 1: Secure localized orthogonal bus tracks
RESONATE 27          # Step 2: Fire dual-path integer split logic loop
COLLAPSE             # Step 3: Check runtime global system invariance
"""

# Compile assembly text straight into raw binary array data
binary_output_stream = compiler_unit.compile_script(sample_script)

if binary_output_stream:
    print(f"Final Executable Binary Byte Array Stream: {list(binary_output_stream)}")
    print(f"Hexadecimal Machine Code Layout: {[hex(b) for b in binary_output_stream]}")
